# configs/train.yaml
train_shards_dir: data/shards_train
eval_shards_dir: data/shards_val   
in_dim: 14
batch_size: 64
num_workers: 4
prefetch: 4
lr: 3e-4
epochs: 8
loss: rmspe       
out_ckpt: artifacts/best.pt
cuda_rmspe: True
